name: Publish VS Code Extension

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install vsce
        run: npm install -g vsce

      - name: Package extension
        run: vsce package

      - name: Publish extension
        run: vsce publish -p ${{ secrets.VSCE_PAT }}

      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./*.vsix
