name: CD Pipeline

on:
  push:
    branches: [ main ]


  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      
      - name: Download extension artifact
        uses: actions/download-artifact@v4
        with:
          name: extension
          path: ./dist
          
      - name: Install vsce
        run: npm install -g vsce
        
      - name: Publish extension
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        
      - name: Upload VSIX as release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ./dist/*.vsix
